# Mental Health Dataset Analysis (DIU Extended Edition)

This notebook loads and analyzes the processed mental health dataset: **"Mental Health Problems of University Students (DIU Extended Edition)"**.

### Dataset Overview:
- **Base dataset:** Standardized dataset on Mental Health Problems (MHPs) of University Students (Syeed et al., 2024, Figshare DOI: [10.6084/m9.figshare.25771164.v1](https://doi.org/10.6084/m9.figshare.25771164.v1)).
- **Extended dataset:** Combined with local DIU-collected responses.
- **Variables:** 
  - Demographics (Age, Gender, University, Department, Academic Year, CGPA, waiver status)
  - PSS-10 scale (Perceived Stress Scale, items PSS1–PSS10, total value, and label)
  - GAD-7 scale (Generalized Anxiety Disorder, items GAD1–GAD7, total value, and label)
  - PHQ-9 scale (Patient Health Questionnaire, items PHQ1–PHQ9, total value, and label)

In [2]:
import os
import pandas as pd
import numpy as np

data_path = "diu-extended-mental-health/data/Updated Processed Diu.csv"

if not os.path.exists(data_path):
    print(f"Error: '{data_path}' not found.")
else:
    df = pd.read_csv(data_path)
    print("\n--- Dataset successfully loaded! ---")
    print(f"Dimensions: {df.shape[0]} rows, {df.shape[1]} columns\n")
    
    print("--- First 5 Rows Preview ---")
    display(df.head())
    
    print("\n--- Dataset Summary ---")
    print(df.info())

--- Dataset successfully loaded! ---
Dimensions: 2039 rows, 39 columns

--- First 5 Rows Preview ---

,Age,Gender,University,Department,Academic_Year,Current_CGPA,waiver_or_scholarship,PSS1,PSS2,PSS3,...,PHQ2,PHQ3,PHQ4,PHQ5,PHQ6,PHQ7,PHQ8,PHQ9,Depression Value,Depression Label
0,18-22,Female,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,Second Year or Equivalent,2.50 - 2.99,No,3.0,4.0,3.0,...,2.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,20.0,Severe Depression
1,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,3.0,3.0,4.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,19.0,Moderately Severe Depression
2,18-22,Male,American International University Bangladesh (...,Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Depression
3,18-22,Male,American International University Bangladesh (...,Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,3.0,1.0,2.0,...,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,14.0,Moderate Depression
4,18-22,Male,North South University (NSU),Engineering - CS / CSE / CSC / Similar to CS,Second Year or Equivalent,2.50 - 2.99,No,4.0,4.0,4.0,...,3.0,3.0,3.0,1.0,3.0,0.0,3.0,3.0,20.0,Severe Depression

--- Dataset Summary ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2039 entries, 0 to 2038
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    2038 non-null   object
 1   Gender                 2038 non-null   object
 2   University             2038 non-null   object
 3   Department             2038 non-null   object
 4   Academic_Year          2038 non-null   object
 5   Current_CGPA           2038 non-null   object
 6   waiver_or_scholarship  2038 non-null   object
 7   PSS1                   2038 non-null   float64
 8   PSS2                   2038 non-null   float64
 9   PSS3                   2038 non-null   float64
 10  PSS4                   2038 non-null   float64
 11  PSS5                   2038 non-null   float64
 12  PSS6                   2038 non-null   float64
 13  PSS7                   2038 non-null   float64
 14  PSS8                   2038 non-null   float64
 15  PSS9                   2038 non-null   float64
 16  PSS10                  2038 non-null   float64
 17  Stress Value           2038 non-null   float64
 18  Stress Label           2038 non-null   object
 19  GAD1                   2038 non-null   float64
 20  GAD2                   2038 non-null   float64
 21  GAD3                   2038 non-null   float64
 22  GAD4                   2038 non-null   float64
 23  GAD5                   2038 non-null   float64
 24  GAD6                   2038 non-null   float64
 25  GAD7                   2038 non-null   float64
 26  Anxiety Value          2038 non-null   float64
 27  Anxiety Label          2038 non-null   object
 28  PHQ1                   2038 non-null   float64
 29  PHQ2                   2038 non-null   float64
 30  PHQ3                   2038 non-null   float64
 31  PHQ4                   2038 non-null   float64
 32  PHQ5                   2038 non-null   float64
 33  PHQ6                   2038 non-null   float64
 34  PHQ7                   2038 non-null   float64
 35  PHQ8                   2038 non-null   float64
 36  PHQ9                   2038 non-null   float64
 37  Depression Value       2038 non-null   float64
 38  Depression Label       2038 non-null   object
dtypes: float64(29), object(10)
memory usage: 621.4+ KB
None

### 1. Demographic Distribution
Let's explore the distribution of key demographic characteristics (Gender, Age group, Academic Year, and Current CGPA class).

In [3]:
if 'df' in locals():
    demographics = ['Gender', 'Age', 'Academic_Year', 'Current_CGPA', 'waiver_or_scholarship']
    for col in demographics:
        if col in df.columns:
            print(f"\n=== Distribution of {col} ===")
            counts = df[col].value_counts(dropna=False)
            pcts = df[col].value_counts(dropna=False, normalize=True) * 100
            summary = pd.DataFrame({'Count': counts, 'Percentage (%)': pcts.round(2)})
            display(summary)
else:
    print("Dataset has not been loaded. Please run the load cell first.")

=== Distribution of Gender ===

                   Count  Percentage (%)
Gender
Male                1415           69.40
Female               613           30.06
Prefer not to say     10            0.49
NaN                    1            0.05

=== Distribution of Age ===

          Count  Percentage (%)
Age
18-22      1304           63.95
23-26       702           34.43
27-30        25            1.23
Below 18      4            0.20
Above 30      3            0.15
NaN           1            0.05

=== Distribution of Academic_Year ===

                           Count  Percentage (%)
Academic_Year
First Year or Equivalent     601           29.48
Third Year or Equivalent     570           27.95
Fourth Year or Equivalent    412           20.21
Second Year or Equivalent    383           18.78
Other                         72            3.53
NaN                            1            0.05

=== Distribution of Current_CGPA ===

              Count  Percentage (%)
Current_CGPA
3.00 - 3.39     586           28.74
3.40 - 3.79     564           27.66
2.50 - 2.99     391           19.18
3.80 - 4.00     241           11.82
Other           171            8.39
Below 2.50       85            4.17
NaN               1            0.05

=== Distribution of waiver_or_scholarship ===

                       Count  Percentage (%)
waiver_or_scholarship
No                      1604           78.67
Yes                      434           21.28
NaN                        1            0.05

### 2. Mental Health Assessment Labels (Stress, Anxiety, Depression)
Let's check the distributions of severity levels for Stress, Anxiety, and Depression.

In [4]:
if 'df' in locals():
    mental_health_labels = ['Stress Label', 'Anxiety Label', 'Depression Label']
    for col in mental_health_labels:
        if col in df.columns:
            print(f"\n=== Distribution of {col} ===")
            counts = df[col].value_counts(dropna=False)
            pcts = df[col].value_counts(dropna=False, normalize=True) * 100
            summary = pd.DataFrame({'Count': counts, 'Percentage (%)': pcts.round(2)})
            display(summary)
else:
    print("Dataset has not been loaded. Please run the load cell first.")

=== Distribution of Stress Label ===

                       Count  Percentage (%)
Stress Label
Moderate Stress         1348           66.11
High Perceived Stress    565           27.71
Low Stress               115            5.64
Moderate                   9            0.44
High                       1            0.05
NaN                        1            0.05

=== Distribution of Anxiety Label ===

                  Count  Percentage (%)
Anxiety Label
Severe Anxiety      744           36.49
Moderate Anxiety    622           30.51
Mild Anxiety        512           25.11
Minimal Anxiety     160            7.85
NaN                   1            0.05

=== Distribution of Depression Label ===

                              Count  Percentage (%)
Depression Label
Moderately Severe Depression    512           25.11
Severe Depression               505           24.77
Moderate Depression             460           22.56
Mild Depression                 420           20.60
Minimal Depression               97            4.76
No Depression                    44            2.16
NaN                               1            0.05

### 3. Correlation Analysis between Mental Health Scales
Let's see if there is any correlation between Perceived Stress, Generalized Anxiety, and Depression raw scores.

In [5]:
if 'df' in locals():
    scale_values = ['Stress Value', 'Anxiety Value', 'Depression Value']
    valid_cols = [c for c in scale_values if c in df.columns]
    if valid_cols:
        print("=== Correlation Matrix ===")
        corr_matrix = df[valid_cols].corr()
        display(corr_matrix.round(4))
        
        print("\n=== Mean and Standard Deviation of Scales ===")
        display(df[valid_cols].describe().loc[['mean', 'std', 'min', 'max']])
else:
    print("Dataset has not been loaded. Please run the load cell first.")

=== Correlation Matrix ===

                  Stress Value  Anxiety Value  Depression Value
Stress Value            1.0000         0.6424            0.5842
Anxiety Value           0.6424         1.0000            0.7700
Depression Value        0.5842         0.7700            1.0000

=== Mean and Standard Deviation of Scales ===

      Stress Value  Anxiety Value  Depression Value
mean     22.984298      12.321884         14.401865
std       6.748788       5.494177          6.664182
min       0.000000       0.000000          0.000000
max      40.000000      21.000000         27.000000

In [6]:
df.value_counts()

Age    Gender  University                                             Department                                    Academic_Year              Current_CGPA  waiver_or_scholarship  PSS1  PSS2  PSS3  PSS4  PSS5  PSS6  PSS7  PSS8  PSS9  PSS10  Stress Value  Stress Label           GAD1  GAD2  GAD3  GAD4  GAD5  GAD6  GAD7  Anxiety Value  Anxiety Label     PHQ1  PHQ2  PHQ3  PHQ4  PHQ5  PHQ6  PHQ7  PHQ8  PHQ9  Depression Value  Depression Label
18-22  Male    BRAC University                                        Engineering - CS / CSE / CSC / Similar to CS  First Year or Equivalent   Below 2.50    No                     4.0   4.0   4.0   4.0   1.0   0.0   4.0   0.0   4.0   4.0    35.0          High Perceived Stress  3.0   2.0   1.0   3.0   3.0   3.0   3.0   18.0           Severe Anxiety    1.0   1.0   1.0   1.0   0.0   3.0   3.0   1.0   3.0   14.0              Moderate Depression    2
               Independent University, Bangladesh (IUB)               Engineering - CS / CSE / CSC / Similar to CS  First Year or Equivalent   3.40 - 3.79   Yes                    2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0    20.0          Moderate Stress        1.0   1.0   1.0   1.0   1.0   1.0   1.0   7.0            Mild Anxiety      1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   9.0               Mild Depression        2
                                                                                                                                                             No                     2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0    20.0          Moderate Stress        1.0   1.0   1.0   1.0   1.0   1.0   1.0   7.0            Mild Anxiety      1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   9.0               Mild Depression        2
               American International University Bangladesh (AIUB)    Engineering - CS / CSE / CSC / Similar to CS  Third Year or Equivalent   3.00 - 3.39   No                     2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0    20.0          Moderate Stress        1.0   1.0   1.0   1.0   1.0   1.0   1.0   7.0            Mild Anxiety      1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   9.0               Mild Depression        2
23-26  Male    Dhaka University (DU)                                  Business and Entrepreneurship Studies         Fourth Year or Equivalent  3.00 - 3.39   No                     3.0   4.0   4.0   3.0   0.0   1.0   1.0   0.0   3.0   4.0    35.0          High Perceived Stress  2.0   3.0   2.0   2.0   3.0   2.0   2.0   16.0           Severe Anxiety    1.0   2.0   2.0   1.0   2.0   3.0   1.0   0.0   2.0   14.0              Moderate Depression    2
                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
27-30  Male    Dhaka University (DU)                                  Business and Entrepreneurship Studies         Second Year or Equivalent  3.40 - 3.79   No                     2.0   2.0   2.0   2.0   4.0   3.0   3.0   3.0   1.0   2.0    14.0          Moderate Stress        0.0   1.0   1.0   1.0   1.0   0.0   1.0   5.0            Mild Anxiety      1.0   1.0   1.0   1.0   1.0   0.0   1.0   1.0   0.0   7.0               Mild Depression        1
                                                                      Other                                         Third Year or Equivalent   2.50 - 2.99   No                     2.0   2.0   2.0   0.0   0.0   0.0   2.0   2.0   2.0   2.0    22.0          Moderate Stress        2.0   2.0   3.0   2.0   3.0   2.0   0.0   14.0           Moderate Anxiety  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0               No Depression          1
               Dhaka University of Engineering and Technology (DUET)  Engineering - CS / CSE / CSC / Similar to CS  Fourth Year or Equivalent  2.50 - 2.99   No                     1.0   1.0   2.0   4.0   2.0   1.0   0.0   0.0   4.0   4.0    29.0          High Perceived Stress  2.0   1.0   1.0   1.0   1.0   1.0   0.0   7.0            Mild Anxiety      3.0   3.0   0.0   1.0   1.0   1.0   0.0   0.0   1.0   10.0              Moderate Depression    1
                                                                                                                                                                                    4.0   2.0   4.0   3.0   3.0   0.0   3.0   3.0   3.0   3.0    26.0          Moderate Stress        3.0   3.0   3.0   2.0   2.0   2.0   3.0   18.0           Severe Anxiety    1.0   0.0   2.0   2.0   1.0   1.0   1.0   1.0   1.0   10.0              Moderate Depression    1
                                                                                                                                               3.00 - 3.39   No                     0.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0   0.0   2.0    16.0          Moderate Stress        0.0   0.0   0.0   3.0   0.0   1.0   0.0   4.0            Minimal Anxiety   3.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   4.0               Minimal Depression     1
Name: count, Length: 2032, dtype: int64

In [7]:
for col in ['Stress Label', 'Anxiety Label', 'Depression Label']:
    counts = df[col].value_counts(dropna=False)
    pcts = df[col].value_counts(dropna=False, normalize=True) * 100
    print(f"\n=== {col} ===")
    print(pd.DataFrame({'Count': counts, 'Pct%': pcts.round(1)}).to_string())

=== Stress Label ===
                       Count  Pct%
Stress Label
Moderate Stress         1348  66.1
High Perceived Stress    565  27.7
Low Stress               115   5.6
Moderate                   9   0.4
High                       1   0.0
NaN                        1   0.0

=== Anxiety Label ===
                  Count  Pct%
Anxiety Label
Severe Anxiety      744  36.5
Moderate Anxiety    622  30.5
Mild Anxiety        512  25.1
Minimal Anxiety     160   7.8
NaN                   1   0.0

=== Depression Label ===
                              Count  Pct%
Depression Label
Moderately Severe Depression    512  25.1
Severe Depression               505  24.8
Moderate Depression             460  22.6
Mild Depression                 420  20.6
Minimal Depression               97   4.8
No Depression                    44   2.2
NaN                               1   0.0

Lets carefully inspect this data deeper to get an idea of what it is trying to tell us...

In [8]:
pd.set_option('display.max_columns', None)
##display all 39 columns 
df.head()

,Age,Gender,University,Department,Academic_Year,Current_CGPA,waiver_or_scholarship,PSS1,PSS2,PSS3,PSS4,PSS5,PSS6,PSS7,PSS8,PSS9,PSS10,Stress Value,Stress Label,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,Anxiety Value,Anxiety Label,PHQ1,PHQ2,PHQ3,PHQ4,PHQ5,PHQ6,PHQ7,PHQ8,PHQ9,Depression Value,Depression Label
0,18-22,Female,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,Second Year or Equivalent,2.50 - 2.99,No,3.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0,4.0,4.0,29.0,High Perceived Stress,2.0,2.0,3.0,2.0,2.0,2.0,2.0,15.0,Severe Anxiety,2.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,20.0,Severe Depression
1,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,3.0,3.0,4.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,24.0,Moderate Stress,1.0,2.0,2.0,1.0,1.0,3.0,2.0,12.0,Moderate Anxiety,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,19.0,Moderately Severe Depression
2,18-22,Male,American International University Bangladesh (...,Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,15.0,Moderate Stress,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Minimal Anxiety,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Depression
3,18-22,Male,American International University Bangladesh (...,Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,3.0,1.0,2.0,1.0,4.0,3.0,2.0,2.0,3.0,2.0,17.0,Moderate Stress,2.0,1.0,1.0,1.0,2.0,1.0,2.0,10.0,Moderate Anxiety,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,14.0,Moderate Depression
4,18-22,Male,North South University (NSU),Engineering - CS / CSE / CSC / Similar to CS,Second Year or Equivalent,2.50 - 2.99,No,4.0,4.0,4.0,2.0,2.0,2.0,0.0,2.0,4.0,4.0,32.0,High Perceived Stress,3.0,0.0,3.0,3.0,1.0,1.0,3.0,14.0,Moderate Anxiety,1.0,3.0,3.0,3.0,1.0,3.0,0.0,3.0,3.0,20.0,Severe Depression

In [9]:
print("=== Missing Values ===")
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)
print(f"\nTotal rows: {len(df)}")

=== Missing Values ===
Age                      1
Gender                   1
University               1
Department               1
Academic_Year            1
Current_CGPA             1
waiver_or_scholarship    1
PSS1                     1
PSS2                     1
PSS3                     1
PSS4                     1
PSS5                     1
PSS6                     1
PSS7                     1
PSS8                     1
PSS9                     1
PSS10                    1
Stress Value             1
Stress Label             1
GAD1                     1
GAD2                     1
GAD3                     1
GAD4                     1
GAD5                     1
GAD6                     1
GAD7                     1
Anxiety Value            1
Anxiety Label            1
PHQ1                     1
PHQ2                     1
PHQ3                     1
PHQ4                     1
PHQ5                     1
PHQ6                     1
PHQ7                     1
PHQ8                     1
PHQ9                     1
Depression Value         1
Depression Label         1
dtype: int64

Total rows: 2039

In [10]:
cats = ['Age', 'Gender', 'University', 'Department', 'Academic_Year', 
        'Current_CGPA', 'waiver_or_scholarship']
for col in cats:
    print(f"\n=== {col} ({df[col].nunique()} unique) ===")
    print(df[col].value_counts(dropna=False).to_string())

=== Age (5 unique) ===
Age
18-22       1304
23-26        702
27-30         25
Below 18       4
Above 30       3
NaN            1

=== Gender (3 unique) ===
Gender
Male                 1415
Female                613
Prefer not to say      10
NaN                     1

=== University (15 unique) ===
University
Independent University, Bangladesh (IUB)                      532
American International University Bangladesh (AIUB)           504
Islamic University of Technology (IUT)                        269
Dhaka University (DU)                                         202
Dhaka University of Engineering and Technology (DUET)         162
North South University (NSU)                                   87
Bangladesh University of Engineering and Technology (BUET)     63
Patuakhali Science and Technology University                   50
East West University (EWU)                                     42
Rajshahi University of Engineering and Technology (RUET)       31
Rajshahi University (RU)                                       23
Daffodil University                                            21
BRAC University                                                20
United International University (UIU)                          18
Bangladesh Agricultural University (BAU)                       14
NaN                                                             1

=== Department (12 unique) ===
Department
Engineering - CS / CSE / CSC / Similar to CS            1416
Business and Entrepreneurship Studies                    145
Engineering - EEE/ ECE / Similar to EEE                  129
Biological Sciences                                       95
Other                                                     79
Engineering - Mechanical Engineering / Similar to ME      68
Engineering - Civil Engineering / Similar to CE           50
Environmental and Life Sciences                           47
Engineering - Other                                        5
Pharmacy and Public Health                                 2
Liberal Arts and Social Sciences                           1
Law and Human Rights                                       1
NaN                                                        1

=== Academic_Year (5 unique) ===
Academic_Year
First Year or Equivalent     601
Third Year or Equivalent     570
Fourth Year or Equivalent    412
Second Year or Equivalent    383
Other                         72
NaN                            1

=== Current_CGPA (6 unique) ===
Current_CGPA
3.00 - 3.39    586
3.40 - 3.79    564
2.50 - 2.99    391
3.80 - 4.00    241
Other          171
Below 2.50      85
NaN              1

=== waiver_or_scholarship (2 unique) ===
waiver_or_scholarship
No     1604
Yes     434
NaN       1

In [11]:
for col in ['Stress Value', 'Anxiety Value', 'Depression Value']:
    print(f"\n=== {col} ===")
    print(df[col].describe().round(2))

=== Stress Value ===
count    2038.00
mean       22.98
std         6.75
min         0.00
25%        19.00
50%        22.00
75%        27.00
max        40.00
Name: Stress Value, dtype: float64

=== Anxiety Value ===
count    2038.00
mean       12.32
std         5.49
min         0.00
25%         8.00
50%        13.00
75%        17.00
max        21.00
Name: Anxiety Value, dtype: float64

=== Depression Value ===
count    2038.00
mean       14.40
std         6.66
min         0.00
25%         9.00
50%        14.00
75%        19.00
max        27.00
Name: Depression Value, dtype: float64

In [12]:
dupes = df.duplicated().sum()
print(f"Duplicate rows: {dupes}")

Duplicate rows: 6

In [13]:
print(f"Duplicate rows: {df.duplicated().sum()}")

Duplicate rows: 6

In [14]:
dupes = df[df.duplicated(keep=False)].sort_values(by=list(df.columns))
print(f"Shape: {dupes.shape}")
display(dupes)

Shape: (12, 39)

,Age,Gender,University,Department,Academic_Year,Current_CGPA,waiver_or_scholarship,PSS1,PSS2,PSS3,PSS4,PSS5,PSS6,PSS7,PSS8,PSS9,PSS10,Stress Value,Stress Label,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,Anxiety Value,Anxiety Label,PHQ1,PHQ2,PHQ3,PHQ4,PHQ5,PHQ6,PHQ7,PHQ8,PHQ9,Depression Value,Depression Label
180,18-22,Male,American International University Bangladesh (...,Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,20.0,Moderate Stress,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,Mild Anxiety,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,Mild Depression
1369,18-22,Male,American International University Bangladesh (...,Engineering - CS / CSE / CSC / Similar to CS,Third Year or Equivalent,3.00 - 3.39,No,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,20.0,Moderate Stress,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,Mild Anxiety,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,Mild Depression
882,18-22,Male,BRAC University,Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,Below 2.50,No,4.0,4.0,4.0,4.0,1.0,0.0,4.0,0.0,4.0,4.0,35.0,High Perceived Stress,3.0,2.0,1.0,3.0,3.0,3.0,3.0,18.0,Severe Anxiety,1.0,1.0,1.0,1.0,0.0,3.0,3.0,1.0,3.0,14.0,Moderate Depression
1120,18-22,Male,BRAC University,Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,Below 2.50,No,4.0,4.0,4.0,4.0,1.0,0.0,4.0,0.0,4.0,4.0,35.0,High Perceived Stress,3.0,2.0,1.0,3.0,3.0,3.0,3.0,18.0,Severe Anxiety,1.0,1.0,1.0,1.0,0.0,3.0,3.0,1.0,3.0,14.0,Moderate Depression
17,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.40 - 3.79,No,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,20.0,Moderate Stress,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,Mild Anxiety,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,Mild Depression
492,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.40 - 3.79,No,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,20.0,Moderate Stress,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,Mild Anxiety,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,Mild Depression
712,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.40 - 3.79,Yes,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,20.0,Moderate Stress,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,Mild Anxiety,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,Mild Depression
763,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.40 - 3.79,Yes,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,20.0,Moderate Stress,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,Mild Anxiety,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,Mild Depression
473,23-26,Male,Dhaka University (DU),Business and Entrepreneurship Studies,Fourth Year or Equivalent,3.00 - 3.39,No,3.0,4.0,4.0,3.0,0.0,1.0,1.0,0.0,3.0,4.0,35.0,High Perceived Stress,2.0,3.0,2.0,2.0,3.0,2.0,2.0,16.0,Severe Anxiety,1.0,2.0,2.0,1.0,2.0,3.0,1.0,0.0,2.0,14.0,Moderate Depression
1362,23-26,Male,Dhaka University (DU),Business and Entrepreneurship Studies,Fourth Year or Equivalent,3.00 - 3.39,No,3.0,4.0,4.0,3.0,0.0,1.0,1.0,0.0,3.0,4.0,35.0,High Perceived Stress,2.0,3.0,2.0,2.0,3.0,2.0,2.0,16.0,Severe Anxiety,1.0,2.0,2.0,1.0,2.0,3.0,1.0,0.0,2.0,14.0,Moderate Depression
54,23-26,Male,Dhaka University (DU),Other,Fourth Year or Equivalent,3.00 - 3.39,Yes,1.0,2.0,3.0,3.0,1.0,0.0,1.0,0.0,3.0,2.0,28.0,High Perceived Stress,1.0,2.0,2.0,3.0,3.0,2.0,3.0,16.0,Severe Anxiety,3.0,3.0,3.0,2.0,1.0,3.0,2.0,2.0,3.0,22.0,Severe Depression
533,23-26,Male,Dhaka University (DU),Other,Fourth Year or Equivalent,3.00 - 3.39,Yes,1.0,2.0,3.0,3.0,1.0,0.0,1.0,0.0,3.0,2.0,28.0,High Perceived Stress,1.0,2.0,2.0,3.0,3.0,2.0,3.0,16.0,Severe Anxiety,3.0,3.0,3.0,2.0,1.0,3.0,2.0,2.0,3.0,22.0,Severe Depression

In [15]:
for scale, items in [('PSS', [f'PSS{i}' for i in range(1,11)]),
                     ('GAD', [f'GAD{i}' for i in range(1,8)]),
                     ('PHQ', [f'PHQ{i}' for i in range(1,10)])]:
    print(f"\n{'='*50}")
    print(f"{scale} ITEM-LEVEL DISTRIBUTIONS")
    print(f"{'='*50}")
    print(df[items].describe().round(2))
    print(f"\nVariance:")
    print(df[items].var().round(3))

==================================================
PSS ITEM-LEVEL DISTRIBUTIONS
==================================================
          PSS1     PSS2     PSS3     PSS4     PSS5     PSS6     PSS7     PSS8  \
count  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00
mean      2.35     2.32     2.71     2.37     2.17     1.79     1.93     1.72
std       1.18     1.16     1.13     1.22     1.09     1.10     1.02     1.13
min       0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00
25%       2.00     2.00     2.00     2.00     2.00     1.00     1.00     1.00
50%       2.00     2.00     3.00     2.00     2.00     2.00     2.00     2.00
75%       3.00     3.00     4.00     3.00     3.00     2.00     3.00     2.00
max       4.00     4.00     4.00     4.00     4.00     4.00     4.00     4.00

          PSS9    PSS10
count  2038.00  2038.00
mean      2.42     2.43
std       1.18     1.17
min       0.00     0.00
25%       2.00     2.00
50%       2.00     2.00
75%       3.00     3.00
max       4.00     4.00

Variance:
PSS1     1.389
PSS2     1.337
PSS3     1.281
PSS4     1.495
PSS5     1.179
PSS6     1.204
PSS7     1.037
PSS8     1.281
PSS9     1.384
PSS10    1.361
dtype: float64

==================================================
GAD ITEM-LEVEL DISTRIBUTIONS
==================================================
          GAD1     GAD2     GAD3     GAD4     GAD5     GAD6     GAD7
count  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00
mean      1.78     1.63     1.75     1.78     1.86     1.79     1.73
std       0.95     1.03     1.00     0.97     0.98     0.99     1.06
min       0.00     0.00     0.00     0.00     0.00     0.00     0.00
25%       1.00     1.00     1.00     1.00     1.00     1.00     1.00
50%       2.00     2.00     2.00     2.00     2.00     2.00     2.00
75%       3.00     3.00     3.00     3.00     3.00     3.00     3.00
max       3.00     3.00     3.00     3.00     3.00     3.00     3.00

Variance:
GAD1    0.906
GAD2    1.054
GAD3    0.990
GAD4    0.932
GAD5    0.966
GAD6    0.985
GAD7    1.118
dtype: float64

==================================================
PHQ ITEM-LEVEL DISTRIBUTIONS
==================================================
          PHQ1     PHQ2     PHQ3     PHQ4     PHQ5     PHQ6     PHQ7     PHQ8  \
count  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00  2038.00
mean      1.46     1.79     1.66     1.95     1.50     1.79     1.64     1.44
std       0.95     1.03     1.06     0.97     1.04     1.07     1.03     1.03
min       0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00
25%       1.00     1.00     1.00     1.00     1.00     1.00     1.00     1.00
50%       1.00     2.00     2.00     2.00     1.00     2.00     2.00     1.00
75%       2.00     3.00     3.00     3.00     2.00     3.00     3.00     2.00
max       3.00     3.00     3.00     3.00     3.00     3.00     3.00     3.00

          PHQ9
count  2038.00
mean      1.17
std       1.14
min       0.00
25%       0.00
50%       1.00
75%       2.00
max       3.00

Variance:
PHQ1    0.911
PHQ2    1.070
PHQ3    1.119
PHQ4    0.949
PHQ5    1.090
PHQ6    1.152
PHQ7    1.052
PHQ8    1.052
PHQ9    1.303
dtype: float64

In [16]:
print("=== Stress vs Anxiety ===")
print(pd.crosstab(df['Stress Label'], df['Anxiety Label'], margins=True))

print("\n=== Stress vs Depression ===")
print(pd.crosstab(df['Stress Label'], df['Depression Label'], margins=True))

print("\n=== Anxiety vs Depression ===")
print(pd.crosstab(df['Anxiety Label'], df['Depression Label'], margins=True))

=== Stress vs Anxiety ===
Anxiety Label          Mild Anxiety  Minimal Anxiety  Moderate Anxiety  \
Stress Label
High                              0                0                 1
High Perceived Stress            24                0               104
Low Stress                       52               40                20
Moderate                          7                1                 1
Moderate Stress                 429              119               496
All                             512              160               622

Anxiety Label          Severe Anxiety   All
Stress Label
High                                0     1
High Perceived Stress             437   565
Low Stress                          3   115
Moderate                            0     9
Moderate Stress                   304  1348
All                               744  2038

=== Stress vs Depression ===
Depression Label       Mild Depression  Minimal Depression  \
Stress Label
High                                 0                   0
High Perceived Stress               13                   1
Low Stress                          48                  28
Moderate                             6                   0
Moderate Stress                    353                  68
All                                420                  97

Depression Label       Moderate Depression  Moderately Severe Depression  \
Stress Label
High                                     1                             0
High Perceived Stress                   69                           183
Low Stress                              23                            10
Moderate                                 2                             1
Moderate Stress                        365                           318
All                                    460                           512

Depression Label       No Depression  Severe Depression   All
Stress Label
High                               0                  0     1
High Perceived Stress              1                298   565
Low Stress                         5                  1   115
Moderate                           0                  0     9
Moderate Stress                   38                206  1348
All                               44                505  2038

=== Anxiety vs Depression ===
Depression Label  Mild Depression  Minimal Depression  Moderate Depression  \
Anxiety Label
Mild Anxiety                  247                  47                  156
Minimal Anxiety                56                  41                   23
Moderate Anxiety              102                   8                  207
Severe Anxiety                 15                   1                   74
All                           420                  97                  460

Depression Label  Moderately Severe Depression  No Depression  \
Anxiety Label
Mild Anxiety                                46              6
Minimal Anxiety                              3             34
Moderate Anxiety                           233              2
Severe Anxiety                             230              2
All                                        512             44

Depression Label  Severe Depression   All
Anxiety Label
Mild Anxiety                     10   512
Minimal Anxiety                   3   160
Moderate Anxiety                 70   622
Severe Anxiety                  422   744
All                             505  2038

In [17]:
for demo in ['Gender', 'Age', 'Academic_Year']:
    for label in ['Stress Label', 'Anxiety Label', 'Depression Label']:
        print(f"\n=== {label} by {demo} ===")
        ct = pd.crosstab(df[demo], df[label], normalize='index').round(3) * 100
        print(ct.to_string())

=== Stress Label by Gender ===
Stress Label       High  High Perceived Stress  Low Stress  Moderate  Moderate Stress
Gender
Female              0.0                   36.1         2.4       0.0             61.5
Male                0.1                   24.0         7.1       0.6             68.2
Prefer not to say   0.0                   40.0         0.0       0.0             60.0

=== Anxiety Label by Gender ===
Anxiety Label      Mild Anxiety  Minimal Anxiety  Moderate Anxiety  Severe Anxiety
Gender
Female                     22.3              4.7              28.7            44.2
Male                       26.4              9.3              31.3            33.0
Prefer not to say          10.0              0.0              30.0            60.0

=== Depression Label by Gender ===
Depression Label   Mild Depression  Minimal Depression  Moderate Depression  Moderately Severe Depression  No Depression  Severe Depression
Gender
Female                        17.9                 4.2                 18.6                          28.1            1.0               30.2
Male                          21.9                 5.0                 24.3                          23.9            2.7               22.2
Prefer not to say              0.0                 0.0                 20.0                          20.0            0.0               60.0

=== Stress Label by Age ===
Stress Label  High  High Perceived Stress  Low Stress  Moderate  Moderate Stress
Age
18-22          0.0                   29.9         5.2       0.0             64.9
23-26          0.1                   23.6         5.8       1.3             69.1
27-30          0.0                   32.0         8.0       0.0             60.0
Above 30       0.0                   33.3        66.7       0.0              0.0
Below 18       0.0                    0.0        50.0       0.0             50.0

=== Anxiety Label by Age ===
Anxiety Label  Mild Anxiety  Minimal Anxiety  Moderate Anxiety  Severe Anxiety
Age
18-22                  24.4              7.6              30.6            37.4
23-26                  26.8              7.7              30.5            35.0
27-30                  16.0             16.0              32.0            36.0
Above 30                0.0             33.3              33.3            33.3
Below 18               50.0             50.0               0.0             0.0

=== Depression Label by Age ===
Depression Label  Mild Depression  Minimal Depression  Moderate Depression  Moderately Severe Depression  No Depression  Severe Depression
Age
18-22                        20.3                 4.7                 22.9                          25.1            1.5               25.5
23-26                        21.5                 4.6                 21.8                          25.5            3.0               23.6
27-30                        12.0                 8.0                 24.0                          20.0           12.0               24.0
Above 30                      0.0                 0.0                 66.7                          33.3            0.0                0.0
Below 18                     25.0                50.0                 25.0                           0.0            0.0                0.0

=== Stress Label by Academic_Year ===
Stress Label               High  High Perceived Stress  Low Stress  Moderate  Moderate Stress
Academic_Year
First Year or Equivalent    0.0                   23.3         7.2       0.0             69.6
Fourth Year or Equivalent   0.2                   25.7         6.6       1.9             65.5
Other                       0.0                   19.4         8.3       0.0             72.2
Second Year or Equivalent   0.0                   35.8         5.2       0.3             58.7
Third Year or Equivalent    0.0                   29.5         3.3       0.0             67.2

=== Anxiety Label by Academic_Year ===
Anxiety Label              Mild Anxiety  Minimal Anxiety  Moderate Anxiety  Severe Anxiety
Academic_Year
First Year or Equivalent           29.8             10.0              29.6            30.6
Fourth Year or Equivalent          29.4              6.8              28.4            35.4
Other                              31.9              5.6              33.3            29.2
Second Year or Equivalent          21.1              6.8              31.9            40.2
Third Year or Equivalent           18.9              7.4              31.8            41.9

=== Depression Label by Academic_Year ===
Depression Label           Mild Depression  Minimal Depression  Moderate Depression  Moderately Severe Depression  No Depression  Severe Depression
Academic_Year
First Year or Equivalent              23.1                 6.5                 25.0                          24.3            2.0               19.1
Fourth Year or Equivalent             21.8                 4.9                 25.7                          23.5            1.9               22.1
Other                                 22.2                 4.2                 20.8                          22.2            4.2               26.4
Second Year or Equivalent             17.0                 5.2                 19.3                          26.4            1.6               30.5
Third Year or Equivalent              19.3                 2.6                 20.2                          26.7            2.6               28.6

In [18]:
pnts = df[df['Gender'] == 'Prefer not to say']
print(f"Rows: {len(pnts)}")
print("\n=== Scale Scores ===")
print(pnts[['Stress Value', 'Anxiety Value', 'Depression Value']].describe().round(2))
print("\n=== Labels ===")
for col in ['Stress Label', 'Anxiety Label', 'Depression Label']:
    print(f"\n{col}:")
    print(pnts[col].value_counts())

Rows: 10

=== Scale Scores ===
       Stress Value  Anxiety Value  Depression Value
count         10.00          10.00             10.00
mean          28.60          15.20             20.50
std            7.78           4.71              6.43
min           19.00           7.00             10.00
25%           22.50          12.25             15.50
50%           26.00          15.50             21.50
75%           36.50          18.75             26.75
max           39.00          21.00             27.00

=== Labels ===

Stress Label:
Stress Label
Moderate Stress          6
High Perceived Stress    4
Name: count, dtype: int64

Anxiety Label:
Anxiety Label
Severe Anxiety      6
Moderate Anxiety    3
Mild Anxiety        1
Name: count, dtype: int64

Depression Label:
Depression Label
Severe Depression               6
Moderate Depression             2
Moderately Severe Depression    2
Name: count, dtype: int64

In [19]:
# PHQ-9 severity bands
phq_bands = [(0,4,'Minimal Depression'), (5,9,'Mild Depression'),
             (10,14,'Moderate Depression'), (15,19,'Moderately Severe Depression'),
             (20,27,'Severe Depression')]

# GAD-7 severity bands
gad_bands = [(0,4,'Minimal Anxiety'), (5,9,'Mild Anxiety'),
             (10,14,'Moderate Anxiety'), (15,21,'Severe Anxiety')]

# PSS-10 severity bands
pss_bands = [(0,13,'Low Stress'), (14,26,'Moderate Stress'),
             (27,40,'High Perceived Stress')]

def check_boundaries(df, value_col, label_col, bands):
    mismatches = []
    for _, row in df.iterrows():
        val = row[value_col]
        actual = row[label_col]
        if pd.isna(val) or pd.isna(actual):
            continue
        expected = None
        for low, high, lbl in bands:
            if low <= val <= high:
                expected = lbl
                break
        if expected != actual:
            mismatches.append({
                'index': _,
                'value': val,
                'expected_label': expected,
                'actual_label': actual
            })
    return pd.DataFrame(mismatches)

print("=== PHQ-9 Boundary Check ===")
phq_issues = check_boundaries(df, 'Depression Value', 'Depression Label', phq_bands)
print(f"Mismatches: {len(phq_issues)}")
if len(phq_issues) > 0:
    display(phq_issues)

print("\n=== GAD-7 Boundary Check ===")
gad_issues = check_boundaries(df, 'Anxiety Value', 'Anxiety Label', gad_bands)
print(f"Mismatches: {len(gad_issues)}")
if len(gad_issues) > 0:
    display(gad_issues)

print("\n=== PSS-10 Boundary Check ===")
pss_issues = check_boundaries(df, 'Stress Value', 'Stress Label', pss_bands)
print(f"Mismatches: {len(pss_issues)}")
if len(pss_issues) > 0:
    display(pss_issues)

=== PHQ-9 Boundary Check ===
Mismatches: 44

    index  value      expected_label   actual_label
0       2    0.0  Minimal Depression  No Depression
1      52    0.0  Minimal Depression  No Depression
2      69    0.0  Minimal Depression  No Depression
3     179    0.0  Minimal Depression  No Depression
4     244    0.0  Minimal Depression  No Depression
5     258    0.0  Minimal Depression  No Depression
6     380    0.0  Minimal Depression  No Depression
7     484    0.0  Minimal Depression  No Depression
8     497    0.0  Minimal Depression  No Depression
9     504    0.0  Minimal Depression  No Depression
10    554    0.0  Minimal Depression  No Depression
11    640    0.0  Minimal Depression  No Depression
12    709    0.0  Minimal Depression  No Depression
13    766    0.0  Minimal Depression  No Depression
14    777    0.0  Minimal Depression  No Depression
15    831    0.0  Minimal Depression  No Depression
16    847    0.0  Minimal Depression  No Depression
17    849    0.0  Minimal Depression  No Depression
18    857    0.0  Minimal Depression  No Depression
19    930    0.0  Minimal Depression  No Depression
20    953    0.0  Minimal Depression  No Depression
21    982    0.0  Minimal Depression  No Depression
22   1113    0.0  Minimal Depression  No Depression
23   1121    0.0  Minimal Depression  No Depression
24   1135    0.0  Minimal Depression  No Depression
25   1147    0.0  Minimal Depression  No Depression
26   1324    0.0  Minimal Depression  No Depression
27   1355    0.0  Minimal Depression  No Depression
28   1391    0.0  Minimal Depression  No Depression
29   1410    0.0  Minimal Depression  No Depression
30   1418    0.0  Minimal Depression  No Depression
31   1488    0.0  Minimal Depression  No Depression
32   1537    0.0  Minimal Depression  No Depression
33   1666    0.0  Minimal Depression  No Depression
34   1709    0.0  Minimal Depression  No Depression
35   1807    0.0  Minimal Depression  No Depression
36   1825    0.0  Minimal Depression  No Depression
37   1828    0.0  Minimal Depression  No Depression
38   1864    0.0  Minimal Depression  No Depression
39   1895    0.0  Minimal Depression  No Depression
40   1920    0.0  Minimal Depression  No Depression
41   1970    0.0  Minimal Depression  No Depression
42   1996    0.0  Minimal Depression  No Depression
43   2010    0.0  Minimal Depression  No Depression

=== GAD-7 Boundary Check ===
Mismatches: 0

=== PSS-10 Boundary Check ===
Mismatches: 10

   index  value         expected_label actual_label
0   2028   16.0        Moderate Stress     Moderate
1   2029   15.0        Moderate Stress     Moderate
2   2030   16.0        Moderate Stress     Moderate
3   2031   23.0        Moderate Stress     Moderate
4   2032   25.0        Moderate Stress     Moderate
5   2033   25.0        Moderate Stress     Moderate
6   2034   21.0        Moderate Stress     Moderate
7   2035   16.0        Moderate Stress     Moderate
8   2036   28.0  High Perceived Stress         High
9   2037   17.0        Moderate Stress     Moderate

In [20]:
from ydata_profiling import ProfileReport

# Path to the dataset
data_path = "diu-extended-mental-health/data/Updated Processed Diu.csv"
output_path = "profile_report.html"

if not os.path.exists(data_path):
    print(f"Error: '{data_path}' not found in the current directory.")
else:
    print("Loading dataset...")
    df = pd.read_csv(data_path)
    
    print("Generating profile report using ydata-profiling...")
    # Generate the Profile Report (explorative=True is recommended for dynamic exploratory analyses)
    profile = ProfileReport(df, title="DIU Extended Mental Health Dataset Profile Report", explorative=True)
    
    print(f"Saving profile report to '{output_path}'...")
    profile.to_file(output_path)
    print("Profile report successfully generated!")

Loading dataset...
Generating profile report using ydata-profiling...
Saving profile report to 'profile_report.html'...

100%|██████████| 39/39 [00:00<00:00, 46.29it/s]1<00:00, 43.46it/s, Describe variable: Depression Label]
Summarize dataset: 100%|██████████| 58/58 [00:10<00:00,  5.71it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:09<00:00,  9.49s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.00s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 54.02it/s]

Profile report successfully generated!

Now after thorough inspection we move onto the cleaining part...

In [21]:
df = df.dropna(how='all').reset_index(drop=True)
print(f"Rows after dropping ghost row: {len(df)}")

Rows after dropping ghost row: 2038

In [22]:
df['Stress Label'] = df['Stress Label'].replace({
    'Moderate': 'Moderate Stress',
    'High': 'High Perceived Stress'
})
print(df['Stress Label'].value_counts())

Stress Label
Moderate Stress          1357
High Perceived Stress     566
Low Stress                115
Name: count, dtype: int64

In [23]:
df = df.drop_duplicates(keep='first').reset_index(drop=True)
print(f"Rows after dropping duplicates: {len(df)}")

Rows after dropping duplicates: 2032

In [24]:
df['Depression Label'] = df['Depression Label'].replace({
    'No Depression': 'Minimal Depression'
})
print(df['Depression Label'].value_counts())

Depression Label
Moderately Severe Depression    512
Severe Depression               504
Moderate Depression             458
Mild Depression                 417
Minimal Depression              141
Name: count, dtype: int64

In [25]:
print(f"Final row count: {len(df)}")
print(f"\nStress Label:\n{df['Stress Label'].value_counts()}")
print(f"\nAnxiety Label:\n{df['Anxiety Label'].value_counts()}")
print(f"\nDepression Label:\n{df['Depression Label'].value_counts()}")
print(f"\nRemaining nulls:\n{df.isnull().sum()[df.isnull().sum() > 0]}")

Final row count: 2032

Stress Label:
Stress Label
Moderate Stress          1354
High Perceived Stress     563
Low Stress                115
Name: count, dtype: int64

Anxiety Label:
Anxiety Label
Severe Anxiety      741
Moderate Anxiety    622
Mild Anxiety        509
Minimal Anxiety     160
Name: count, dtype: int64

Depression Label:
Depression Label
Moderately Severe Depression    512
Severe Depression               504
Moderate Depression             458
Mild Depression                 417
Minimal Depression              141
Name: count, dtype: int64

Remaining nulls:
Series([], dtype: int64)

In [26]:
df.to_csv('mental_health_cleaned.csv', index=False)